---
# - include_role:
#     name: "./../../monetdb_farm"

- name: Upload VOC data
  copy:
    src: .monetdb
    dest: "{{ monetdb_work_dir }}"

- name: Unpack VOC data
  unarchive:
    src: voc.tar.gz
    dest: "{{ monetdb_work_dir }}"

- name: Create VOC database
  shell: "monetdb create -p monetdb voc"

- name: Load VOC data
  shell: "mclient -d voc {{ monetdb_work_dir }}/voc_dump.sql"

# - name:
