# Set to false if you don't have root rights.
# In that case you have to install the build dependencies manually.
can_sudo: yes

# Location of the MonetDB sources
monetdb_mirror: https://www.monetdb.org/downloads/sources/
monetdb_source_url: "{{ monetdb_mirror }}/{{ monetdb_release }}/MonetDB-{% if monetdb_version is defined %}{{ monetdb_version }}{% else %}{{ monetdb_version_for_release[monetdb_release] }}{% endif %}.tar.xz"

# Mercurial repository to fetch the MonetDB source from
hg_repo: https://dev.monetdb.org/hg/MonetDB

monetdb_src: "{{monetdb_prefix}}/src"
build_dir: "{{monetdb_prefix}}/build"
monetdb_configure_flags: --enable-optimize --disable-debug --disable-assert --disable-developer
# --disable-pyintegration --disable-py3integration

